In [7]:
import torch
import numpy as np

파이토치 텐서 생성하기

In [6]:
ft = torch.FloatTensor([[1, 2],[3, 4]])
print(ft)

lt = torch.LongTensor([[1, 2],[3, 4]])
print(lt)

bt = torch.ByteTensor([[1, 0],[0, 1]])
print(bt)

# 임의의 값으로 채워진 원하는 크기의 텐서 
x = torch.FloatTensor(3, 2)
print(x)



tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)
tensor([[0.0000e+00, 7.4269e-44],
        [2.1159e+23, 1.3434e-05],
        [2.0546e+20, 1.0812e-05]])


넘파이 호환

In [14]:
# 넘파이 배열 
x1 = np.array([[1, 2],[3, 4]])
print(x1, type(x1))

print('='*50)
# 넘파이 배열 -> 파이토치 텐서로 변환 
x2 = torch.from_numpy(x1)
print(x2, type(x2))


print('='*50)
# 파이토치 텐서 -> 넘파이 배열로 변환
x3 = x2.numpy()
print(x3, type(x3))


[[1 2]
 [3 4]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>


텐서 타입 변환 

In [19]:
print(f'float->long : {ft.long()}')

print(f'long->float : {lt.float()}')

float->long : tensor([[1, 2],
        [3, 4]])
long->float : tensor([[1., 2.],
        [3., 4.]])


텐서 크기 구하기

In [28]:
x = torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(x.size())
print(x.shape)

# 텐서 차원의 개수 
print(x.dim())
print(len(x.size()))

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])
3
3


기본 연산 : 메모리에 새롭게 할당

In [49]:
a = torch.FloatTensor([[1,2],[3,4]])
b = torch.FloatTensor([[2,2],[3,3]])

print(f'+ : {a+b}')
print(f'- : {a-b}')
print(f'* : {a*b}')
print(f'/ : {a/b}')
print(f'** : {a**b}')
print(f'== : {a==b}')
print(f'!= : {a!=b}')





+ : tensor([[3., 4.],
        [6., 7.]])
- : tensor([[-1.,  0.],
        [ 0.,  1.]])
* : tensor([[ 2.,  4.],
        [ 9., 12.]])
/ : tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])
** : tensor([[ 1.,  4.],
        [27., 64.]])
== : tensor([[False,  True],
        [ True, False]])
!= : tensor([[ True, False],
        [False,  True]])


인플레이스 연산 : 기존 텐서에 결과 저장

In [50]:
# 기존 연산방법 -> a 본래의 값은 바뀌지 않음 
print(f'a : {a}')
print(f'mul(*) : {a.mul(b)}')
print(f'new_a : {a}')

a : tensor([[1., 2.],
        [3., 4.]])
mul(*) : tensor([[ 2.,  4.],
        [ 9., 12.]])
new_a : tensor([[1., 2.],
        [3., 4.]])


In [52]:
# 인플레이스 연산방법 -> a 본래의 값이 바뀜 
print(f'a : {a}')
print(f'inplace mul_() : {a.mul_(b)}')
print(f'new_inplace_a : {a}')

a : tensor([[ 2.,  4.],
        [ 9., 12.]])
inplace mul_() : tensor([[ 4.,  8.],
        [27., 36.]])
new_inplace_a : tensor([[ 4.,  8.],
        [27., 36.]])


차원 축소 연산 

In [58]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[[1,2,3],[4,5,6],[7,8,9]]])

# sum() / mean() 함수를 통해 차원 축소 
print(f'sum : {x.sum()}')
print(f'mean : {x.mean()}')

print(f'dim=0 : {x.sum(dim=0)}')
print(f'dim=1 : {x.sum(dim=1)}')
print(f'dim=2 : {y.sum(dim=2)}')

sum : 10.0
mean : 2.5
dim=0 : tensor([4., 6.])
dim=1 : tensor([3., 7.])
dim=2 : tensor([[ 6., 15., 24.]])


브로드캐스트 연산 : 크기가 다른 텐서 연산 

In [79]:
# tensor + scalar
x = torch.FloatTensor([[1,2],[3,4]])
y = 1
z = x+y
print(f'x+y : {z}')
print(f'size : {z.size()}')

print('='*50)

# tensor + vector 
x1 = torch.FloatTensor([[1,2],[4,8]]) # 2*2
y1 = torch.FloatTensor([3, 5]) # 1*2
z1 = x1+y1

print(f'x1+y1 : {z1}')
print(f'size : {z.size()}')

print('='*50)

# tensor + tensor 
x2 = torch.FloatTensor([[1,2]]) # 1*2
y2 = torch.FloatTensor([[3],[5]]) # 2*1
z2 = x2+y2
print(f'x2+y2 : {z2}')
print(f'size : {z2.size()}')



x+y : tensor([[2., 3.],
        [4., 5.]])
size : torch.Size([2, 2])
x1+y1 : tensor([[ 4.,  7.],
        [ 7., 13.]])
size : torch.Size([2, 2])
x2+y2 : tensor([[4., 5.],
        [6., 7.]])
size : torch.Size([2, 2])


텐서 형태 변환

In [102]:
# view 함수 

x = torch.FloatTensor([[[1,2],
                        [3,4]],
                        [[5,6],
                        [7,8]],
                        [[9,10],
                        [11,12]]])
print(f'size : {x.size()}')
print('\n')
print(x)
print(x.view(12)) # 1*12 = 12
print(x.view(3,4)) # 3*4 = 12
print(x.view(3,1,4)) # (1*4) * 3 = 12
print(x.view(3,2,2)) # (2*2) * 3 = 12

# -1 을 활용하면 곱하고 남은 필요한 값을 자동으로 채워줌 
print(x.view(3,-1)) 
print(x.view(4,-1))

size : torch.Size([3, 2, 2])


tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


Squeeze 함수 : 차원 삭제 

In [117]:
x = torch.FloatTensor([[[1,2],
                        [3,4]]])

print(x)
#print(x.size())

print(x.squeeze())
#print(x.squeeze().size())

print(f'Before : {x.size()} -> After : {x.squeeze().size()}')

print('='*100)

print(x.squeeze(0).size())
print(x.squeeze(1).size())

tensor([[[1., 2.],
         [3., 4.]]])
tensor([[1., 2.],
        [3., 4.]])
Before : torch.Size([1, 2, 2]) -> After : torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([1, 2, 2])


Unsqueeze 함수 : 차원 삽입

In [125]:
x = torch.FloatTensor([[1,2],
                        [3,4]])
print(x.size())

print(x.unsqueeze(1).size())
print(x.unsqueeze(-1).size())
print(x.unsqueeze(2).size())
# reshape 함수로 똑같이 구현가능 
print(x.reshape(2, 2, -1).size())



torch.Size([2, 2])
torch.Size([2, 1, 2])
torch.Size([2, 2, 1])
torch.Size([2, 2, 1])
torch.Size([2, 2, 1])


텐서 자르기&붙이기

In [143]:
# indexing/slicing 함수
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                        [[5,6],
                        [7,8]],
                        [[9,10],
                        [11,12]]])

print(x.size)
print(x)

print(f'x[0] : \n{x[0]}')
print(f'x[-1]) : \n{x[-1]}')

print(f'x[:,0] : \n{x[:,0]}')

<built-in method size of Tensor object at 0x00000275FD5FEC40>
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
x[0] : 
tensor([[1., 2.],
        [3., 4.]])
x[-1]) : 
tensor([[ 9., 10.],
        [11., 12.]])
x[:,0] : 
tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [153]:
# split 함수 : 특정 차원에 대해 원하는 크기로 잘라줌 
 
x = torch.FloatTensor(10, 4) # 10*4
print(f'before : \n{x}')
print(f'After : \n{x.split(4,dim=0)}')

splits = x.split(4, dim=0)
for s in splits:
    print(s.size())


before : 
tensor([[9.9184e-39, 9.0000e-39, 1.0561e-38, 1.0653e-38],
        [4.1327e-39, 8.9082e-39, 9.8265e-39, 9.4592e-39],
        [1.0561e-38, 1.0653e-38, 1.0469e-38, 9.5510e-39],
        [9.1837e-39, 1.0561e-38, 1.0469e-38, 9.0000e-39],
        [1.0653e-38, 1.0194e-38, 1.0561e-38, 8.7245e-39],
        [1.0286e-38, 9.0919e-39, 9.0919e-39, 9.2755e-39],
        [8.7245e-39, 9.9184e-39, 9.4592e-39, 1.0561e-38],
        [9.6429e-39, 8.7245e-39, 1.0194e-38, 1.0010e-38],
        [9.9184e-39, 9.0918e-39, 1.1112e-38, 9.5511e-39],
        [1.0102e-38, 4.6837e-39, 4.2245e-39, 1.1112e-38]])
After : 
(tensor([[9.9184e-39, 9.0000e-39, 1.0561e-38, 1.0653e-38],
        [4.1327e-39, 8.9082e-39, 9.8265e-39, 9.4592e-39],
        [1.0561e-38, 1.0653e-38, 1.0469e-38, 9.5510e-39],
        [9.1837e-39, 1.0561e-38, 1.0469e-38, 9.0000e-39]]), tensor([[1.0653e-38, 1.0194e-38, 1.0561e-38, 8.7245e-39],
        [1.0286e-38, 9.0919e-39, 9.0919e-39, 9.2755e-39],
        [8.7245e-39, 9.9184e-39, 9.4592e-39, 1.05

In [157]:
# Chunk 함수 : 크기에 상관 없이 원하는 개수로 나눔

x = torch.FloatTensor(8,4) # 8*4
print(f'before : \n{x}')
print(f'After : \n{x.chunk(3,dim=0)}')


chunks = x.chunk(3, dim=0) 
for c in chunks:
    print(c.size())


before : 
tensor([[1.4013e-43, 4.4842e-44, 1.6255e-43, 1.4714e-43],
        [1.5274e-43, 1.4153e-43, 4.4842e-44, 1.3593e-43],
        [1.5414e-43, 1.4013e-43, 4.4842e-44, 1.5134e-43],
        [1.4714e-43, 1.5414e-43, 1.4153e-43, 4.4842e-44],
        [1.3873e-43, 1.5554e-43, 1.6395e-43, 1.5414e-43],
        [1.6255e-43, 5.7453e-44, 1.4013e-44, 4.4842e-44],
        [4.4842e-44, 4.4842e-44, 4.4842e-44, 4.4842e-44],
        [4.4842e-44, 4.4842e-44, 4.4842e-44, 4.4842e-44]])
After : 
(tensor([[1.4013e-43, 4.4842e-44, 1.6255e-43, 1.4714e-43],
        [1.5274e-43, 1.4153e-43, 4.4842e-44, 1.3593e-43],
        [1.5414e-43, 1.4013e-43, 4.4842e-44, 1.5134e-43]]), tensor([[1.4714e-43, 1.5414e-43, 1.4153e-43, 4.4842e-44],
        [1.3873e-43, 1.5554e-43, 1.6395e-43, 1.5414e-43],
        [1.6255e-43, 5.7453e-44, 1.4013e-44, 4.4842e-44]]), tensor([[4.4842e-44, 4.4842e-44, 4.4842e-44, 4.4842e-44],
        [4.4842e-44, 4.4842e-44, 4.4842e-44, 4.4842e-44]]))
torch.Size([3, 4])
torch.Size([3, 4])
torch.S

In [169]:
# index Select 함수 
x = torch.FloatTensor([[[1,1],
                        [2,2]],
                        [[3,3],
                        [4,4]],
                        [[5,5],
                        [6,6]]])
print(x)
print(x.size())                        
print('='*100)

indice = torch.LongTensor([2,1])
y = x.index_select(dim=0, index=indice)
print(y)
print(y.size())

tensor([[[1., 1.],
         [2., 2.]],

        [[3., 3.],
         [4., 4.]],

        [[5., 5.],
         [6., 6.]]])
torch.Size([3, 2, 2])
tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


In [178]:
# Concatenate 함수 : 차원의 크기가 같아야함 
x = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

y = torch.FloatTensor([[10,11,12],
                       [13,14,15],
                       [16,17,18]])

print(x.size(), y.size())
                       
z1 = torch.cat([x,y], dim=0) # dim=0 : 세로 
print(z1)
print(z1.size())

print('='*100)

z2 = torch.cat([x,y], dim=-1) # dim=-1 : 마지막 차원으로 텐서를 이어 붙임 
print(z2)
print(z2.size())

torch.Size([3, 3]) torch.Size([3, 3])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])
tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


In [190]:
# Stack 함수 
print(x.size())
print(y.size())

print('='*100)

z = torch.stack([x,y]) # 세로로 쌓기 
print(z)
print(z.size())

print('='*100)

z1 = torch.stack([x,y], dim=-1) 
print(z1)
print(z1.size())

torch.Size([3, 3])
torch.Size([3, 3])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])
tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


유용한 함수들 

In [196]:
# Expand 함수 : 차원의 크기를 늘려줌

x = torch.FloatTensor([[[1,2]],
                       [[3,4]]])
print(x)
print(f'x.size : {x.size()}')

y = x.expand(2,3,2)
print(y)
print(f'y.size : {y.size()}')

tensor([[[1., 2.]],

        [[3., 4.]]])
x.size : torch.Size([2, 1, 2])
tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
y.size : torch.Size([2, 3, 2])


In [198]:
# Random Permutation 함수 : 랜덤 수열 생성 함수 
x = torch.randperm(10)
print(x)

print(x.size())

tensor([9, 4, 8, 1, 2, 7, 3, 5, 6, 0])
torch.Size([10])


In [211]:
# Argument Max 함수 : 가장 큰 값 인덱스 추출 
x = torch.randperm(3**3).reshape(3,3,-1)
print(x)
print(x.size())

y = x.argmax(dim=-1)
print(y)
print(y.size())


tensor([[[ 2,  0, 21],
         [17, 24,  3],
         [16, 22,  9]],

        [[25, 19, 14],
         [10,  8, 13],
         [20,  6,  5]],

        [[ 7,  1, 23],
         [26, 12, 18],
         [11,  4, 15]]])
torch.Size([3, 3, 3])
tensor([[2, 1, 1],
        [0, 2, 0],
        [2, 0, 2]])
torch.Size([3, 3])


In [228]:
# Top-k 함수 : argmax 와 비슷, 가장 큰 k개의 값과 인덱스를 모두 반환 

values, indices = torch.topk(x, k=1, dim=-1)
print(values) # 값 반환
print(values.size())
print(indices) # 인덱스 반환 
print(indices.size())

_, indices = torch.topk(x, k=2, dim=-1)
print(indices.size())

tensor([[[21],
         [24],
         [22]],

        [[25],
         [13],
         [20]],

        [[23],
         [26],
         [15]]])
torch.Size([3, 3, 1])
tensor([[[2],
         [1],
         [1]],

        [[0],
         [2],
         [0]],

        [[2],
         [0],
         [2]]])
torch.Size([3, 3, 1])
torch.Size([3, 3, 2])


In [233]:
# Sort 함수 : 정렬함수 
print(x)

x_sort = x.sort()
print(x_sort)

tensor([[[ 2,  0, 21],
         [17, 24,  3],
         [16, 22,  9]],

        [[25, 19, 14],
         [10,  8, 13],
         [20,  6,  5]],

        [[ 7,  1, 23],
         [26, 12, 18],
         [11,  4, 15]]])
torch.return_types.sort(
values=tensor([[[ 0,  2, 21],
         [ 3, 17, 24],
         [ 9, 16, 22]],

        [[14, 19, 25],
         [ 8, 10, 13],
         [ 5,  6, 20]],

        [[ 1,  7, 23],
         [12, 18, 26],
         [ 4, 11, 15]]]),
indices=tensor([[[1, 0, 2],
         [2, 0, 1],
         [2, 0, 1]],

        [[2, 1, 0],
         [1, 0, 2],
         [2, 1, 0]],

        [[1, 0, 2],
         [1, 2, 0],
         [1, 0, 2]]]))


In [239]:
# Masked Fill 함수 : 텐서 내의 원하는 부분만 특정 값으로 바꿈 
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3,-1)
print(x)
print(x.size())

# 논리연산자 
mask = x>4 # Boolean tensor 로 변환 
print(mask)

y = x.masked_fill(mask, value=-1) # 4보다 큰 값을 -1로 바꿈 
print(y)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


In [243]:
# Ones & Zeros 함수 
print(torch.ones(2,3))
print(torch.zeros(2,3))

x = torch.FloatTensor([[1,2,3], [4,5,6]])

# Ones_like & Zeros_like 를 통해 특정 텐서와 같은 크기의 0&1 텐서 만들기 가능 
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
